services:
  prefect-worker:
    image: custom-prefect-worker:3.6.13-python3.12
    build:
      context: ../..       # <--- Sobe de prefect-worker -> _ops -> raiz                
      dockerfile: _ops/prefect-worker/Dockerfile # <--- Caminho a partir da raiz
    restart: always
    volumes:
      - ../../:/app                        # <--- Mapeia a raiz do projeto para /app
      - C:/deploy_metadata:/app/_metadata  # <--- Mapeia a pasta de metadata para dentro do container
    env_file:
      - .env.worker
    environment:
      - PYTHONPATH=/app:/app/flows_prefect:/app/tasks_python
      - PREFECT_API_URL=http://192.168.21.251:4200/api
      - TZ=America/Sao_Paulo
      - PREFECT_WORKER_HEARTBEAT_SECONDS=15
    command: >
      sh -c "
        prefect worker start --pool process-pool --work-queue default --limit 3 --name $${WORKER_NAME}
      "